apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-deployment
  labels:
    app: driver-deployment
spec:
  selector:
     matchLabels:
       app: driver-deployment
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: driver-deployment
    spec:
      containers:
        - image: charlesjiang1997/driver:v1
          imagePullPolicy: Always
          name: driver-deployment
          ports:
            - containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: LoadBalancer
  ports:
  - name: driver
    port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app:  driver-deployment
