apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deployment
  labels:
    app: sonar-deployment
spec:
  selector:
     matchLabels:
       app: sonar-deployment
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sonar-deployment
    spec:
      containers:
        - image: charlesjiang1997/sonar:v1
          imagePullPolicy: Always
          name: sonar-deployment
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonar-deployment
