apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
  labels:
    app: spark-deployment
spec:
  selector:
     matchLabels:
       app: spark-deployment
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: spark-deployment
    spec:
      containers:
        - image: charlesjiang1997/spark:v1
          imagePullPolicy: Always
          name: spark-deployment
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spark-deployment